/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class DataStore {
  constructor()
  /**
   * Sets a key-value pair in this DataStore instance.
   * The value can be any valid JSON structure (object, array, string, number, boolean, null).
   */
  setItem(key: string, value: JsonValue): void
  /**
   * Gets a value by key from this DataStore instance.
   * Returns the value as a JSON structure.
   */
  getItem(key: string): JsonValue | null
  /** Removes an item by key from this DataStore instance. */
  removeItem(key: string): JsonValue | null
  /** Clears all items from this DataStore instance. */
  clear(): void
  /** Returns the number of items in this DataStore instance. */
  size(): number
}
