/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface QueryResultItem {
  key: string
  value: JsonValue
}
export interface FindResults {
  documents: Array<JsonValue>
  totalCount: number
}
export declare class DataStore {
  constructor()
  insert(documents: Array<JsonValue>): void
  delete(query: { where?: any}): void
  findDocuments(query: { where?: any, sort?: string, page?: number, size?: number }): FindResults
  clear(): void
  size(): number
}
